# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

sphinx:
   configuration: doc/conf.py

# Equivalent to: pip install .[doc]
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
