name: Build/test suite

on:
  push:
    branches:
      mainline
  pull_request:
    branches:
      mainline

jobs:
  build:
    name: |
      ${{ matrix.os }}, numpy==${{ matrix.numpy }}, scipy==${{ matrix.scipy }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            numpy: "1.16"
            scipy: "1.4"
            python: "3.6"
          - os: ubuntu-latest
            numpy: auto
            scipy: auto
            python: "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install numpy ${{ matrix.numpy }}, scipy ${{ matrix.scipy }}
        if: ${{ matrix.numpy != 'auto' }}
        run: |
          pip install numpy==${{ matrix.numpy}} scipy==${{ matrix.scipy }}

      - name: Install package with testing dependencies
        run: |
          pip install .[test]

      - name: Test with pytest
        run: |
          pytest
